version: '3.8'

services:
  be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cubex-health-api-backend
    restart: always
    env_file:
      - .env.production
    ports:
      - 8001:8001 # shifted for local development
    depends_on:
      - db
      - redis
  db:
    image: netreconlab/hipaa-postgres:latest
    container_name: cubex-health-api-postgres
    restart: always
    env_file:
      - pgadmin.env
    ports:
      - 5433:5433 # shifted for local development
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: cubex-health-api-pgadmin
    restart: always
    ports:
      - '5051:80' # shifted for local development
    env_file:
      - pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
  # monitor:
  #   image: percona/pmm-server:2
  #   container_name: cubex-health-api-monitor
  #   restart: always
  #   ports:
  #     - 1080:80 # Unsecure connections
  #     - 1443:443 # Secure connections
  #   environment:
  #     - pgadmin.env
  #   volumes:
  #     - pmm-data:/srv
  #   depends_on:
  #     - db
  schemaspy:
    image: schemaspy/schemaspy:snapshot
    volumes:
      - ./schemaspy/output:/output
      - ./schemaspy/config:/config
    container_name: 'schemaspy_local'
    command:
      ['-configFile', '/config/schemaspy.properties', '-imageformat', 'svg']
    depends_on:
      - db
  redis:
    image: redis
    container_name: cubex-health-api-redis
    command: --port 6380
    ports:
      - '6380:6380'
    volumes:
      - redis-data:/var/lib/redis

volumes:
  db_data:
  pgadmin-data:
  redis-data:
  # pmm-data:
